# Generated by Django 3.1.5 on 2021-01-29 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='branch name')),
                ('location', models.CharField(max_length=20, verbose_name='branch address')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branch',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=50, verbose_name='car manufacturer')),
                ('model', models.CharField(blank=True, max_length=50, null=True, verbose_name='car model')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='car color')),
                ('gear', models.CharField(max_length=50, verbose_name='gear box type')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='car number')),
                ('type', models.CharField(max_length=20, verbose_name='car type')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='human name')),
                ('last_name', models.CharField(max_length=100, verbose_name='human last name')),
                ('phone', models.CharField(max_length=20, verbose_name='phone number')),
                ('Added', models.DateTimeField(auto_now_add=True, verbose_name='Added Date/Time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated Date/Time')),
            ],
            options={
                'verbose_name': 'Human',
                'verbose_name_plural': 'Humans',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=50, verbose_name='position')),
                ('salary', models.CharField(max_length=20, verbose_name='salary')),
                ('job_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wash.branch')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wash.human')),
            ],
            options={
                'verbose_name': 'Worker',
                'verbose_name_plural': 'Staff',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.CharField(max_length=20, verbose_name='cost')),
                ('started', models.DateTimeField(auto_now_add=True, verbose_name='Started Date/Time')),
                ('ended', models.DateTimeField(blank=True, null=True, verbose_name='Ended Date/Time')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wash.car')),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wash.human')),
                ('washer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wash.staff')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wash.human'),
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='box number')),
                ('is_free', models.BooleanField(default=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wash.branch')),
            ],
            options={
                'verbose_name': 'Box',
                'verbose_name_plural': 'Boxes',
            },
        ),
    ]
