# Generated by Django 3.1.5 on 2021-01-29 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wash', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='name',
            new_name='human',
        ),
    ]
